"""MuJoCo stand-in for a real Skate: same UDP wire protocol, same port.

Run this and anything written for the physical robot — the official teleop
client, the skate_ros2 driver, your own code — connects to it unmodified:

    python3 -m skate_ros2.sim_endpoint --model /path/to/skt_v3_control.xml
    # then point clients at 127.0.0.1 instead of r.local

The model is the control-ready MJCF generated by ``skatearm/sim/
make_control_model.py`` (26 position actuators over the official skt_v3 twin).

Faithful to the firmware contract:
* listens on UDP :2000, streams telemetry to whoever spoke last;
* telemetry = pickled ``(id, obj)`` with the official classes (ids 0–3);
* accepts ``(5, (targ_pos, vel_cmd, height_cmd, deadman))`` commands;
* firmware watchdog: nothing heard for 0.3 s -> deadman assumed (0,0,0).

Honest approximations (documented, not hidden):
* "dampen" freezes position targets at the current pose instead of dropping
  to kd-only damping like the real firmware;
* motor temperatures are SYNTHETIC (warm up with |torque|, cool toward 25 °C)
  so temperature plumbing can be exercised end-to-end;
* ``vel_cmd``/``height_cmd`` are accepted but ignored — the control model has
  a fixed base (no wheel actuators yet);
* INS stream reports a static upright pose.
"""

from __future__ import annotations

import argparse
import pickle
import socket
import time

import numpy as np

from . import names
from . import shared_classes_def as SCD
from .protocol import (BUFFER_SIZE, COMMAND_ID, DEFAULT_PORT, STALE_AFTER,
                       unpack_packet)


class SkateSimEndpoint:
    def __init__(self, model_path, port=DEFAULT_PORT, telemetry_hz=50.0,
                 bind="0.0.0.0", realtime=True, verbose=True):
        import mujoco  # local import: protocol users shouldn't need mujoco
        self._mujoco = mujoco
        self.m = mujoco.MjModel.from_xml_path(str(model_path))
        self.d = mujoco.MjData(self.m)
        if self.m.nu != names.N_JOINTS:
            raise ValueError(
                f"expected {names.N_JOINTS} actuators, model has {self.m.nu} "
                "— use the control-ready MJCF from sim/make_control_model.py")
        # actuator i drives joint i in protocol order (verified at load):
        for i in range(names.N_JOINTS):
            jname = self.m.joint(self.m.actuator(i).trnid[0]).name
            if jname != names.JOINT_NAMES[i]:
                raise ValueError(
                    f"actuator {i} drives '{jname}', expected "
                    f"'{names.JOINT_NAMES[i]}' — wrong/reordered model?")
        self.lo = self.m.actuator_ctrlrange[:, 0].copy()
        self.hi = self.m.actuator_ctrlrange[:, 1].copy()

        self.port = port
        self.telemetry_period = 1.0 / float(telemetry_hz)
        self.realtime = realtime
        self.verbose = verbose

        self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.sock.setblocking(False)
        self.sock.bind((bind, port))

        self.client = None            # (ip, port) of last sender
        self.last_rx_wall = 0.0       # wall clock of last client packet
        self.last_cmd = None          # (targ, vel, height, deadman)
        self.dampened = True          # start dampened, like the real robot
        self.temps = np.full(names.N_JOINTS, 25.0)
        self.n_cmds = 0
        self.n_telemetry = 0
        self.decode_errors = 0
        self._stop = False

        # settle into the model's initial pose
        self.d.ctrl[:] = np.clip(self.d.qpos[:names.N_JOINTS], self.lo, self.hi)

    # -- network ------------------------------------------------------------
    def pump_network(self):
        """Drain inbound packets: heartbeats register the client, id=5 commands
        update targets. Returns number of packets seen."""
        n = 0
        while True:
            try:
                data, addr = self.sock.recvfrom(BUFFER_SIZE)
            except (BlockingIOError, OSError):
                break
            n += 1
            self.client = addr
            self.last_rx_wall = time.monotonic()
            if data == b"yo" or len(data) < 8:
                continue  # heartbeat
            try:
                pkt_id, payload = unpack_packet(data)
            except Exception:
                self.decode_errors += 1
                continue
            if pkt_id != COMMAND_ID:
                continue
            try:
                targ, vel, height, deadman = payload
                targ = np.asarray(targ, dtype=np.float64).reshape(names.N_JOINTS)
                self.last_cmd = (targ, np.asarray(vel, dtype=np.float64),
                                 float(height), tuple(int(x) for x in deadman))
                self.n_cmds += 1
            except Exception:
                self.decode_errors += 1
        return n

    def _apply_command(self):
        """Translate last command + watchdog into actuator targets."""
        silent = (time.monotonic() - self.last_rx_wall) > STALE_AFTER
        if self.last_cmd is None or self.client is None or silent:
            deadman = (0, 0, 0)
            targ = None
        else:
            targ, _vel, _height, deadman = self.last_cmd

        wb, la, ra = deadman
        if wb == 0 or targ is None:
            # whole-body dampen: freeze at current pose (approximation)
            if not self.dampened:
                self.d.ctrl[:] = np.clip(self.d.qpos[:names.N_JOINTS],
                                         self.lo, self.hi)
            self.dampened = True
            return
        self.dampened = False
        ctrl = np.clip(targ, self.lo, self.hi)
        if la == 0:  # left arm dampened: hold current
            ctrl[names.LEFT_ARM] = self.d.qpos[names.LEFT_ARM]
        if ra == 0:
            ctrl[names.RIGHT_ARM] = self.d.qpos[names.RIGHT_ARM]
        self.d.ctrl[:] = ctrl

    # -- telemetry ------------------------------------------------------------
    def _update_temps(self, dt):
        tau = np.abs(self.d.actuator_force[:names.N_JOINTS])
        target = 25.0 + 30.0 * (tau / 28.0)         # 28 N·m = spec torque
        alpha = min(1.0, dt / 5.0)                   # ~5 s thermal time const
        self.temps += alpha * (target - self.temps)

    def _send(self, pkt_id, obj):
        try:
            self.sock.sendto(pickle.dumps((pkt_id, obj)), self.client)
            self.n_telemetry += 1
        except OSError:
            pass

    def send_telemetry(self):
        if self.client is None:
            return
        q = self.d.qpos[:names.N_JOINTS]
        v = self.d.qvel[:names.N_JOINTS]
        tau = self.d.actuator_force[:names.N_JOINTS]

        ms = SCD.motor_state()
        ms.motor_pos = names.vector_to_can_dict(q)
        ms.motor_vel = names.vector_to_can_dict(v)
        ms.motor_torque = names.vector_to_can_dict(tau)
        ms.motor_temp = names.vector_to_can_dict(self.temps)
        self._send(1, ms)

        se = SCD.state_est()
        se.dof_pos = names.vector_to_can_dict(q)      # sim: calibrated == raw
        se.dof_vel = names.vector_to_can_dict(v)
        se.dof_torque = names.vector_to_can_dict(tau)
        self._send(2, se)

        ins = SCD.INS_fusion_state()
        ins.out_quat = np.array([1.0, 0.0, 0.0, 0.0])  # static upright (w,x,y,z)
        ins.out_grav_vec = np.array([0.0, 0.0, -9.81])
        self._send(3, ins)

        if self.last_cmd is not None:
            mc = SCD.motor_command()
            mc.motor_pos_cmd = names.vector_to_can_dict(
                self.d.ctrl[:names.N_JOINTS])
            self._send(0, mc)

    # -- main loop ------------------------------------------------------------
    def run(self, duration=None):
        mujoco = self._mujoco
        dt = self.m.opt.timestep
        t_wall0 = time.monotonic()
        next_telemetry = 0.0
        next_log = 0.0
        if self.verbose:
            print(f"[sim_endpoint] skt_v3 twin on UDP :{self.port} "
                  f"(telemetry {1/self.telemetry_period:.0f} Hz, "
                  f"{'realtime' if self.realtime else 'fast'} physics)")
        while not self._stop:
            sim_t = self.d.time
            wall_t = time.monotonic() - t_wall0
            if duration is not None and sim_t >= duration:
                break
            if self.realtime and sim_t > wall_t:
                time.sleep(min(sim_t - wall_t, 0.005))
                continue

            self.pump_network()
            self._apply_command()
            mujoco.mj_step(self.m, self.d)

            clock = wall_t if self.realtime else sim_t
            if clock >= next_telemetry:
                self._update_temps(self.telemetry_period)
                self.send_telemetry()
                next_telemetry = clock + self.telemetry_period
            if self.verbose and clock >= next_log:
                state = "DAMPENED" if self.dampened else "active"
                print(f"[sim_endpoint] t={sim_t:7.2f}s client={self.client} "
                      f"cmds={self.n_cmds} telemetry={self.n_telemetry} "
                      f"[{state}]")
                next_log = clock + 2.0

    def close(self):
        """Stop the run loop (if any) and release the socket — safe to call
        from another thread; embedders should join their thread after this."""
        self._stop = True
        self.sock.close()


def main(argv=None):
    import os
    ap = argparse.ArgumentParser(
        description="Skate UDP endpoint backed by the MuJoCo skt_v3 twin")
    ap.add_argument("--model", default=os.environ.get("SKATE_MJCF"),
                    help="path to skt_v3_control.xml (or set $SKATE_MJCF); "
                         "generate it with skatearm/sim/make_control_model.py")
    ap.add_argument("--port", type=int, default=DEFAULT_PORT)
    ap.add_argument("--rate", type=float, default=50.0,
                    help="telemetry rate, Hz (default 50)")
    ap.add_argument("--duration", type=float, default=None,
                    help="exit after N seconds of sim time (default: forever)")
    ap.add_argument("--fast", action="store_true",
                    help="run physics as fast as possible (testing)")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args(argv)
    if not args.model:
        ap.error("--model is required (or set $SKATE_MJCF). Generate the "
                 "control-ready MJCF with skatearm/sim/make_control_model.py "
                 "over your Rbotic/skate_teleop clone.")
    ep = SkateSimEndpoint(args.model, port=args.port, telemetry_hz=args.rate,
                          realtime=not args.fast, verbose=not args.quiet)
    try:
        ep.run(duration=args.duration)
    except KeyboardInterrupt:
        pass
    finally:
        ep.close()


if __name__ == "__main__":
    main()
